spring:
  main:
    lazy-initialization: true
  datasource:
    url: jdbc:mysql://localhost/db-jestor-app?createDatabaseIfNotExist=true&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
    username: root
    password: 12345
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  flyway:
    locations: classpath:db/migration,classpath:db/testdata
  cache:
    type: redis
    redis:
      host: localhost
      port: 6379
      password:
      connect-timeout-seconds: 5
      command-timeout-seconds: 5
      time-to-live: 30
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 1800000  # 30 minutes
      refresh-token:
        expiration: 3600000 # 1 hour