spring:
  datasource:
    url: jdbc:mysql://localhost/jestor?createDatabaseIfNotExist=true&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
    username: root
    password: 12345
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  flyway:
    locations: classpath:db/migration,classpath:db/testdata
  cache:
    type: redis
    redis:
      host: localhost
      port: 6379
      time-to-live: 2000000
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 1800000  # 30 minutes
      refresh-token:
        expiration: 3600000 # 1 hour
