spring:
  datasource:
    url: jdbc:mysql://localhost/jestor?createDatabaseIfNotExist=true&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
    username: root
    password: 12345
  jpa:
    hibernate:
#      ddl-auto: update
    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  flyway:
    locations: classpath:db/migration,classpath:db/testdata

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 900000  # 15 minutes
      refresh-token:
        expiration: 3600000 # 1 hour
